sft-alpaca-mixtral-mixtral:
  batch_size: 1
  completion_parser_kwargs:
    outputs_to_match:
      1: Output \(a\)
      2: Output \(b\)
  completions_kwargs:
    batch_size: 4
    is_fast_tokenizer: true
    max_new_tokens: 10
    model_kwargs:
      load_in_4bit: true
    model_name: model_ckpts/mixtral-alpaca-mixtral_test/epoch_1/merged_model
  fn_completions: huggingface_local_completions
  prompt_template: huggingface_models/basic_prompt.txt
